/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
FilterGuiDemoAudioProcessor::FilterGuiDemoAudioProcessor()
{
}

FilterGuiDemoAudioProcessor::~FilterGuiDemoAudioProcessor()
{
}

//==============================================================================
const String FilterGuiDemoAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

bool FilterGuiDemoAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool FilterGuiDemoAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool FilterGuiDemoAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double FilterGuiDemoAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int FilterGuiDemoAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int FilterGuiDemoAudioProcessor::getCurrentProgram()
{
    return 0;
}

void FilterGuiDemoAudioProcessor::setCurrentProgram (int index)
{
}

const String FilterGuiDemoAudioProcessor::getProgramName (int index)
{
    return String();
}

void FilterGuiDemoAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void FilterGuiDemoAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void FilterGuiDemoAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

template <typename FloatType>
void FilterGuiDemoAudioProcessor::process (AudioBuffer<FloatType>& buffer,
                                                MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getTotalNumInputChannels(); i < getTotalNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());

    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    for (int channel = 0; channel < getTotalNumInputChannels(); ++channel)
    {
        float* channelData = buffer.getWritePointer (channel);

        // ..do something to the data...
    }
}

//==============================================================================
bool FilterGuiDemoAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* FilterGuiDemoAudioProcessor::createEditor()
{
    return new FilterGuiDemoAudioProcessorEditor (*this);
}

//==============================================================================
void FilterGuiDemoAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void FilterGuiDemoAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new FilterGuiDemoAudioProcessor();
}
